import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import BabyGoose from '../src/components/BabyGoose.jsx';
import KpIcon from '../src/components/KpIcon.jsx';
import tofu from '../src/assets/dish-mapo-tofu.png';
import soup from '../src/assets/dish-noodle-soup.png';
import '../src/styles/tokens.css';
import '../src/styles/design-v4.css';
import '../src/pages/LiveCookPage.css';
import './cook-summary-options.css';

const steps = ['Dice onion, carrot & celery','Measure stock, bay leaf & thyme','Mince garlic','Sauté onion, carrot & celery','Trim & season chicken','Portion & season ground pork','Mince ginger & scallion','Cut tofu into cubes','Brown pork, then fry doubanjiang & aromatics'];
function Players({compact=false}) {return <div className={`cs-players ${compact?'compact':''}`}><div><img src="/avatars/1123.png" alt=""/><span><strong>Zoe</strong><small>15 steps done</small></span><b>229</b></div><div><img src="/avatars/1116.png" alt=""/><span><strong>Kai</strong><small>4 steps done</small></span><b>50</b></div></div>;}
function Receipt(){return <article className="cs-receipt" aria-label="Kitchen receipt"><header><KpIcon glyph="pot" size={25}/><h2>KITCHEN PATH</h2><span>ONE KITCHEN · TWO COOKS</span></header><div className="cs-receipt-meta"><span>COOK RECEIPT / 001</span><span>VERSUS</span></div><div className="cs-receipt-items"><span className="cs-label">WHAT WE MADE</span><p><b>01</b><strong>Mapo tofu</strong><span>✓</span></p><p><b>01</b><strong>Chicken noodle soup</strong><span>✓</span></p></div><div className="cs-receipt-totals"><p><span>Dishes served</span><b>2</b></p><p><span>Steps completed</span><b>19 / 19</b></p><p><span>Steps skipped</span><b>0</b></p><p className="cs-receipt-time"><span>TIME ON THE CLOCK</span><b>3:27</b></p></div><div className="cs-receipt-by"><span className="cs-label">PREPARED TOGETHER BY</span><Players compact/></div><div className="cs-receipt-result"><KpIcon glyph="trophy" size={17}/><strong>Zoe wins this round</strong><span>229 : 50</span></div><footer><BabyGoose pose="g11-handoff" size={72} decorative paused/><div><strong>THANKS FOR COOKING TOGETHER.</strong><span>See you at the next dinner.</span></div></footer><div className="cs-barcode" aria-hidden="true"/><div className="cs-receipt-id">KP · 2 COOKS · 2 DISHES · 19 STEPS</div></article>;}
function Collectible(){const [back,setBack]=useState(false);return <article className="cs-collectible lc-piece" aria-label="Recipe collectible card"><header><span><KpIcon glyph="fork-branch" size={17}/> COOK COLLECTION</span><b>001</b></header><div className="cs-card-body"><div className="cs-card-title"><span className="cs-label">COOKED TOGETHER</span><h2>Mapo Tofu +<br/>Chicken Noodle Soup</h2></div>{!back?<div className="cs-card-art"><div><img src={tofu} alt="Mapo tofu"/><span>01 / MAPO TOFU</span></div><div><img src={soup} alt="Chicken noodle soup"/><span>02 / CHICKEN SOUP</span></div><span className="cs-card-sticker">19/19<br/><small>DONE</small></span></div>:<div className="cs-card-back"><span className="cs-label">THE COOK, IN NUMBERS</span><h3>Different hands.<br/>Same dinner.</h3><p>Zoe completed 15 steps.<br/>Kai completed 4 steps.<br/>All 19 steps were marked done.</p><span>Recorded time · 3:27</span></div>}<div className="cs-card-stats"><span><KpIcon glyph="timer" size={18}/><strong>3:27</strong><small>on the clock</small></span><span><strong>2</strong><small>dishes made</small></span><span><strong>0</strong><small>skipped</small></span></div><Players/><div className="cs-card-victory"><BabyGoose pose="g9-victory" size={76} decorative/><span><small>VERSUS RESULT</small><strong>Zoe wins this round.</strong></span><KpIcon glyph="trophy" size={21}/></div></div><footer><span>MADE BY ZOE × KAI</span><button onClick={()=>setBack(!back)} aria-pressed={back}>{back?'Show dishes':'Flip card'} ↻</button></footer></article>;}
function App(){const [variant,setVariant]=useState('receipt');return <div className="cs-page ds-v4 ds-v4-layer"><nav className="cs-top"><a href="/"><span className="cs-brand-icon"><KpIcon glyph="fork-branch" size={21}/></span>Kitchen Path</a><span>DESIGN PREVIEW</span></nav><div className="cs-switcher"><div><strong>结算页 · 两个方向</strong><span>同一套字体、配色、组件边框；只比较左侧形态。</span></div><div role="group" aria-label="Choose summary design"><button aria-pressed={variant==='receipt'} onClick={()=>setVariant('receipt')}>A · 厨房小票</button><button aria-pressed={variant==='card'} onClick={()=>setVariant('card')}>B · 食谱收藏卡</button></div></div><div className="cs-context"><span>Step 5 of 5 · Live cook</span><a href="/">Exit to Home</a></div><h1 className="cs-run-title"><KpIcon glyph="fork-branch" size={22}/>Mapo Tofu + Chicken Noodle Soup <span><KpIcon glyph="trophy" size={15}/>Versus</span></h1><main className={`cs-layout is-${variant}`}><section className="cs-left"><div className="cs-status"><span className="cs-label">SERVICE DONE</span><span className="cs-status-check">✓ Dinner’s up</span></div>{variant==='receipt'?<Receipt/>:<Collectible/>}<button className="cs-print btn btn-primary" onClick={()=>window.print()}>{variant==='receipt'?'Print the cook receipt':'Print the cook card'} <span>↗</span></button><p className="cs-option-note">{variant==='receipt'?'A / 小票：保留一顿饭的记录，轻巧、直接。':'B / 收藏卡：两道菜组成一张卡，更接近现有游戏风格。'}</p></section><section className="cs-steps lc-piece"><header><h2>Every step</h2><span>19 done · 0 skipped</span></header><div className="cs-step-list">{steps.map((label,i)=><div key={label}><span>{label}</span><small>est {['4:00','1:00','2:00','5:00','2:00','1:30','1:30','3:00','4:00'][i]} · actual {['0:10','0:23','0:01','0:00'][Math.min(i,3)]}</small></div>)}</div><footer>展示截图中的步骤节选 · 示例数据</footer></section></main><p className="cs-preview-note">设计预览：沿用截图中的选手、比分与时间；未接入真实比赛或收藏存储。</p></div>;}
createRoot(document.getElementById('root')).render(<App/>);
