from pathlib import Path
import json
B=Path(__file__).resolve().parents[1]/'src/assets/baby-goose-final/animated'
m=json.loads((B/'manifest.json').read_text())
labels={'g1-on-it':'认真炒菜','g2-up-next':'下一个我来','g3-waiting':'趴着等你','g4-free-hands':'双手有空','g5-done-for-the-night':'今晚下班','g6-eyeing-the-offer':'好奇看看','g7-due-honk':'Honk 提醒','g8-toque-neutral':'Toque 待命','g8x-toque-speaking-left':'Toque 向左说话','g8y-toque-calling-right':'Toque 向右说话','g9-victory':'胜利','g10-walking':'走路','g11-handoff':'交接','g12-behind-plan':'落后进度','g13-listening':'认真听','g14-defeat-good-game':'Good game'}
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Baby goose · 动画库</title><style>
*{box-sizing:border-box}body{margin:0;padding:28px;background:#f5f1e9;color:#28241f;font:15px system-ui}main{max-width:1200px;margin:auto}h1{font-size:30px;margin:6px 0}p{line-height:1.7;color:#81766b}.controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:22px 0}button,select{font:inherit;padding:10px 18px;border:1px solid #d6cbba;background:white;border-radius:22px;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}article{min-width:0;background:white;padding:16px;border:1px solid #e4d9c8;border-radius:20px}h2{font-size:16px;margin:0}.stage{height:230px;display:flex;align-items:center;justify-content:center}.sprite{width:100%;aspect-ratio:1;background-image:var(--sheet);background-size:var(--sheet-size) 100%;background-repeat:no-repeat;animation:frames calc(var(--duration) * var(--tempo,1)) steps(var(--frames)) infinite;background-color:white}@keyframes frames{to{background-position-x:var(--travel)}}.stage .sprite{max-width:230px}.paused .sprite{animation-play-state:paused}.samples{display:flex;gap:12px;align-items:center;border-top:1px solid #eee5d8;padding-top:8px}.samples .sprite{width:32px;flex-shrink:0}.samples .medium{width:64px}.samples small{color:#988976;font-size:11px}.links{display:flex;gap:12px;margin-top:10px}a{color:#806343;font-size:12px}.original{display:none;width:230px;max-width:100%}.compare .stage .sprite{display:none}.compare .original{display:block}code{font-size:12px}@media(prefers-reduced-motion:reduce){.sprite{animation:none}}@media(max-width:540px){body{padding:16px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}article{padding:10px}.stage{height:150px}.samples{gap:8px}.samples small{display:none}.samples .medium{width:48px}h2{font-size:13px}.links{gap:6px}}
</style><body><main><p>定稿 baby goose / 白底逐帧动画</p><h1>16 种状态，一套可以直接用的小鹅。</h1><p>WebP 放进网页即可播放。PNG 精灵图与 React 组件支持暂停、调速，以及系统减少动态效果设置。</p><div class="controls"><button id="play" aria-pressed="false">暂停</button><select id="speed" aria-label="播放速度"><option value="1.5">慢一点</option><option value="1" selected>正常速度</option><option value="0.7">快一点</option></select><button id="compare" aria-pressed="false">对照定稿原图</button><a href="baby-goose-web-animation.zip" download>下载网页动画包</a></div><div class="grid">'''
for name,label in labels.items():
 if name not in m:continue
 c=m[name];style=f'--sheet:url({c["sprite"]});--duration:{c["duration"]}ms;--frames:{c["frames"]};--sheet-size:{c["frames"]*100}%;--travel:{100*c["frames"]/(c["frames"]-1)}%'
 html+=f'<article data-pose="{name}" style="{style}"><h2>{label}</h2><div class="stage"><div class="sprite" role="img" aria-label="{label}"></div><img class="original" src="../png/goose-{name}.png" alt="定稿原图"></div><div class="samples"><div class="sprite" aria-hidden="true"></div><small>32px</small><div class="sprite medium" aria-hidden="true"></div><small>64px</small></div><div class="links"><a href="{c["webp"]}" download>WebP 动图</a><a href="{c["sprite"]}" download>PNG 帧图</a></div></article>'
html+='''</div><p>4 张原始动作帧；多数状态往返播放，走路为完整交替步态。白色背景非透明，生成帧之间可能有轻微线条变化。</p></main><script>document.querySelector('#play').onclick=e=>{const v=document.body.classList.toggle('paused');e.target.textContent=v?'播放':'暂停';e.target.setAttribute('aria-pressed',v)};document.querySelector('#speed').onchange=e=>document.body.style.setProperty('--tempo',e.target.value);document.querySelector('#compare').onclick=e=>{const v=document.body.classList.toggle('compare');e.target.textContent=v?'返回动画':'对照定稿原图';e.target.setAttribute('aria-pressed',v)};</script></body></html>'''
(B/'preview.html').write_text(html)
