from pathlib import Path
import json
BASE=Path(__file__).resolve().parents[1]/'src/assets/goose-postures/raster-animated'
manifest=json.loads((BASE/'manifest.json').read_text())
labels={'g1-on-it':'认真炒菜','g2-up-next':'我下一个','g3-waiting':'趴着等你','g4-free-hands':'我来帮忙','g5-done-for-the-night':'下班睡觉','g6-up-for-grabs':'试探着接活','g7-honk':'Honk 提醒','g9-victory':'安静庆祝','toque-idle':'Toque 待命','toque-left':'向左说话','toque-right':'向右说话'}
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>原画版 · 鹅的动作小剧场</title><style>
*{box-sizing:border-box}body{margin:0;padding:30px;background:#f6f0e4;color:#25221e;font:15px system-ui}main{max-width:1160px;margin:auto}h1{font-size:32px;margin:8px 0}p{color:#81796c;line-height:1.7}.controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:22px 0}button,select{font:inherit;padding:9px 16px;border:1px solid #d9cdbb;border-radius:20px;background:#fffcf7;color:#30271d;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:18px}article{background:#fffcf7;border:1px solid #e1d6c5;border-radius:22px;padding:18px}h2{font-size:16px;margin:0}.stage{height:245px;display:flex;justify-content:center;align-items:center}.sprite{width:100%;aspect-ratio:1;background-image:var(--sheet);background-size:600% 100%;background-repeat:no-repeat;animation:frames calc(var(--duration) * var(--tempo,1)) steps(6) infinite}.stage .sprite{width:245px;max-width:100%}@keyframes frames{to{background-position-x:120%}}.paused .sprite{animation-play-state:paused}.original{display:none;width:245px;max-width:100%}.compare .stage .sprite{display:none}.compare .original{display:block}.samples{display:flex;align-items:center;gap:14px;border-top:1px solid #eee2d0;padding-top:10px}.samples .sprite{width:32px;flex-shrink:0}.samples .medium{width:64px}.samples span{font-size:11px;color:#9a8e7a}.links{display:flex;gap:14px;margin-top:12px}a{color:#786041;font-size:12px}.dark{background:#262630;color:#fbf7ef}.dark article{background:#393943;border-color:#53535f}.dark p{color:#c4bcc8}.dark a{color:#dacbb4}@media(prefers-reduced-motion:reduce){.sprite{animation:none}}@media(max-width:540px){body{padding:16px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}article{padding:12px;min-width:0}.stage{min-width:0}.stage{height:155px}h1{font-size:26px}h2{font-size:14px}.links{gap:8px}.samples{gap:8px}.samples .medium{width:48px}.samples span{display:none}}
</style><body><main><p>PNG 原画风格 / 透明逐帧动画</p><h1>还是刚才那群圆乎乎的鹅。</h1><p>保留粗黑线、圆翅膀和原来的比例，重新生成动作帧。可以暂停逐个看，也可以切回原 PNG 对照。</p><div class="controls"><button id="play" aria-pressed="false">暂停</button><select id="speed" aria-label="播放速度"><option value="1.5">慢一点</option><option selected value="1">正常速度</option><option value="0.7">快一点</option></select><button id="compare" aria-pressed="false">对照原 PNG</button><button id="theme">深色背景</button><a href="goose-raster-animations.zip" download>下载整套动画</a></div><div class="grid">'''
for name,m in manifest.items():
 style=f'--sheet:url({m["sprite"]});--duration:{m["duration"]}ms'
 html+=f'<article data-pose="{name}" style="{style}"><h2>{labels[name]}</h2><div class="stage"><div class="sprite" role="img" aria-label="{labels[name]}"></div><img class="original" src="../png/goose-{name}.png" alt="原始 PNG"></div><div class="samples"><div class="sprite" aria-hidden="true"></div><span>32px</span><div class="sprite medium" aria-hidden="true"></div><span>64px</span></div><div class="links"><a href="{m["webp"]}" download>WebP 动图</a><a href="{m["sprite"]}" download>PNG 帧图</a></div></article>'
html+='''</div><p>WebP 可直接放入网页 &lt;img&gt;；PNG 精灵图支持暂停和调速。每个循环使用 4 张生成帧往返播放，属于轻量逐帧动画，仍可能有轻微帧间线条变化。</p></main><script>
document.querySelector('#play').onclick=e=>{const p=document.body.classList.toggle('paused');e.target.textContent=p?'播放':'暂停';e.target.setAttribute('aria-pressed',p)};document.querySelector('#speed').onchange=e=>document.body.style.setProperty('--tempo',e.target.value);document.querySelector('#compare').onclick=e=>{const p=document.body.classList.toggle('compare');e.target.textContent=p?'返回动画':'对照原 PNG';e.target.setAttribute('aria-pressed',p)};document.querySelector('#theme').onclick=e=>{const p=document.body.classList.toggle('dark');e.target.textContent=p?'浅色背景':'深色背景'};
</script></body></html>'''
(BASE/'preview.html').write_text(html)
